# Generated by Django 4.0.4 on 2022-05-27 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('product', models.CharField(choices=[('strawberries', 'Strawberries'), ('blueberries', 'Blueberries'), ('raspberries', 'Raspberries'), ('blackberries', 'Blackberries'), ('cherries', 'Cherries'), ('jam', 'Jam'), ('farm visit', 'Farm Visit')], default='farm visit', max_length=15)),
                ('rating', models.CharField(choices=[('1 star', '1 Star'), ('2 stars', '2 Stars'), ('3 stars', '3 Stars'), ('4 stars', '4 Stars'), ('5 stars', '5 Stars')], default='5 stars', max_length=15)),
                ('comment', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
