# Generated by Django 4.0.4 on 2022-06-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berrylush_app', '0003_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
