# Generated by Django 4.0.4 on 2022-06-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berrylush_app', '0004_rename_products_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
