# Generated by Django 4.0.4 on 2022-06-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berrylush_app', '0006_product_category_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Jam', 'JAM'), ('Berries', 'BERRIES'), ('Experiences', 'EXPERIENCES')], max_length=256, null=True),
        ),
    ]
