# Generated by Django 4.0.4 on 2022-06-06 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berrylush_app', '0004_product_category'),
        ('berrylush_app', '0015_alter_review_owner'),
    ]

    operations = [
    ]
