# Generated by Django 4.0.4 on 2022-06-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berrylush_app', '0016_merge_0004_product_category_0015_alter_review_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Jam', 'JAM'), ('Berries', 'BERRIES'), ('Experiences', 'EXPERIENCES')], max_length=256, null=True),
        ),
    ]
